### ISSUE TITLE
Inaccurate Build Instructions

### ISSUE THREAD

**Issue by The2b** [immunant/selfrando#12]
The build instructions for Linux were never updated for the changed merging the GCC/Clang wrappers, still saying you should go into the now-nonexistent GCC or Clang folder. Also, the instruction to manually define "arch" were never changed when x86 became the default architecture instead of x86_64, still saying 32-bit archs must explicitly state their arch, instead of 64-bit doing so.

A corrected version is here: http://pastebin.com/cf78J6a6
However, this should still be reviewed in case I made any errors.

**Comment by ahomescu** [comment]
Thanks for catching that.
The target arch should be x86_64 by default, that got switched by mistake. I'll fix it.
The rest should be easy to fix.
