### ISSUE TITLE
COPY relocations for function pointers are broken

### ISSUE THREAD

**Issue by ahomescu** [immunant/selfrando#14]
If a binary contains COPY relocations for data that contains any function pointers, those pointers get copied before randomization and not updated after.

One way to fix this is to add export trampolines for all functions whose pointers are stored in global or read-only data. This would also include function pointers inside vtables.

There may be a non-negligible performance impact to this, so we may need to make this feature optional.

**Comment by thedataking** [comment]
note to self: turned off sanity testing of apache on teamcity until this issue gets resolved.

**Comment by ahomescu** [comment]
Simplest way to get around this issue: compile PIC binaries with `-fPIC` or `-fPIE`.

**Comment by ahomescu** [comment]
We added a pseudo-fix for this in commit https://github.com/immunant/selfrando/commit/128cb0ef546c940c9c104bb981f7a85a1a32dd60 by making TrapLinker exit with error when it detects COPY relocations.
