### ISSUE TITLE
Address ACE 6.4.2 testsuite failures

### ISSUE THREAD

**Issue by thedataking** [immunant/selfrando#17]
Multiple tests fail with selfrando is enabled. Use internal test script `test_ace.py` to reproduce.

**Comment by thedataking** [comment]
Just re-ran the ACE tests with the newest version of selfrando on Ubuntu 16.04. Failures:
```
ERROR:root:test MT_Reference_Counted_Notify_Test failed
ERROR:root:test Bug_3974_Regression_Test failed
ERROR:root:test Bug_2659_Regression_Test failed
ERROR:root:test Thread_Pool_Reactor_Resume_Test failed
ERROR:root:test Bug_2653_Regression_Test failed
ERROR:root:test MT_Reactor_Upcall_Test failed
ERROR:root:test Thread_Pool_Reactor_Test failed
ERROR:root:test Reactor_Registration_Test failed
```
(Also updated test_ACE.py to blacklist an additional failing test).

**Comment by ahomescu** [comment]
This is due to issue #14. Compiling ACE in PIC mode (with `-fPIC`) fixes this by eliminating the copy relocations.
