### ISSUE TITLE
Warn when applying selfrando to code containing COPY relocations on Linux

### ISSUE THREAD

**Issue by thedataking** [immunant/selfrando#35]
Selfrando is currently not compatible with ELF binaries containing copy relocations. See issue #14. The current solution is to compile with -fPIC/-fPIE. Selfrando should warn if producing a linked binary containing copy relocations.

**Comment by ahomescu** [comment]
Fixed in commit https://github.com/immunant/selfrando/commit/128cb0ef546c940c9c104bb981f7a85a1a32dd60.
