### ISSUE TITLE
Build on Arch Linux failled

### ISSUE THREAD

**Issue by yurizhykin** [immunant/selfrando#4]
Tried building on Arch Linux, and failed because of missing `#include <vector>` in `PatchEntry/posix/PatchEntry.cpp`. Here is fix PR, if needed #3

**Comment by ahomescu** [comment]
Merged your commit, looks good.

**Comment by yurizhykin** [comment]
BTW, great work. Currently studying paper and trying to build Bitcoin Core with it.
