### ISSUE TITLE
srenv wrapper doesn't add absolute path to $PATH

### ISSUE THREAD

**Issue by zachriggle** [immunant/selfrando#47]
The `srenv` wrapper uses the (potentially relative) path to itself provided as `argv[0]` to determine its location when populating path.  This causes issues with complex build systems which change the working directory (whereas `$PATH` will continue to contain e.g. `../selfrando/<etc>`).

The `srenv` script should be updated to ensure that it adds an absolute path to `$PATH` (i.e., that it starts with `/`).

An alternate mechanism might be to use `readlink -e` or `realpath` to determine the full path, and use that instead.

**Comment by ahomescu** [comment]
Commit https://github.com/immunant/selfrando/commit/13b99e4a6e4b0965e7610ab8bed07c3840ebd32d should fix this, unless I missed something.

**Comment by zachriggle** [comment]
LGTM! Thanks!
